POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhlc3N1IiwiaWQiOiI1ZjMwZjJjZjIwNWEzNzA0ODA2YzFkZDYiLCJpYXQiOjE1OTcxMjIxNTF9.EE7n9ATQNisUjZzxJmZLnFSD9I9E1inxG67JRJ6xjoY

{
    "title": "Milla Magian blogi",
    "author": "Milla Magia",
    "url": "milla.fi",
    "likes": 290
    
}